
url: https://hilaryokello.github.io
baseurl: /


title: Onyango Okello | IT Consultancy
description: >- # this means to ignore newlines until "baseurl:"
  An IT Consultancy with a focus on the Construction Industry. We create simple and creative websites and applications, develope software solutions, and design data, automation and AI solutions to improve business processes. 



collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "tools.html"
    values:
      layout: "default"
  - scope:
      path: "projects.html"
    values:
      layout: "default"
  - scope:
      path: "website.html"
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# contact form action
contact_form_action: "https://formspree.io/f/mgegygyv"

#   # Build settings
# markdown: kramdown
# permalink: pretty
# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll/tagging

# paginate: 6
# paginate_path: "/page/:num"