########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Projects, url: "projects.html" }
    - { name: Services, url: "#services" }
    - { name: About, url: "#about" }
    - { name: Tools, url: "tools.html" }
    - { name: Get in Touch, url: "#contact" }
  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Projects, url: "projects.html" }
    - { name: Services, url: "#services" }
    - { name: About, url: "#about" }
    - { name: Tools, url: "tools.html" }
    - { name: Get in Touch, url: "#contact" } 

# copyright
copyright: "Copyright &copy; 2024 Designed and Developed by [Onyango Okello](https://onyangookello.com)"

# logo
logo: "/assets/images/logo.svg"

# google analitycs ID
google_analitycs_id: "" # your id

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

######################### Hero Area ##############################
hero_area:
  background_image : "/assets/images/streets.svg"
  image : "/assets/images/city.svg"
  button:
    enable : true
    label : "Get in Touch"
    link : "#"

########################### Service ##############################
services:
- title : "Digital Branding"
  icon : "ti-announcement"
  content : "We tailor solutions to elevate your brand's online presence so you can navigate the digital landscape with confidence."
  link : "branding" 
  label: "See Pricing"

- title : "Web Design & Development"
  icon : "ti-mobile"
  content : "Engage your audience effectively with captivating online experiences and seamless functionality. Contact us today for your website."
  link : "website-pricing"
  label: "See Pricing"

- title : "Data, Automation & AI"
  icon : "ti-dashboard"
  content : "We help harness the power of data analytics for informed decision-making. Streamline operations through automation and AI. Reach out to embark on the future."
  link: "#contact"
  label: "Make an Inquiry"

- title : "Technology Consulting"
  icon : "ti-agenda"
  content : "IT is a wide industry and it can be overwhelming to get started. We'll guide you on the best IT solutions to meet your needs."
  link: "#contact"
  label: "Make an Inquiry"

########################### Website Pricing ##############################

#### website-pricing-intro ####
website-intro:
  - title: "Our Website Design Packages"
    intro-message: "Our website packages have been tailored to offer value for money depending on what you want to achieve. Select from one of our packages below:"
    warning: "Note: Services tangential to website design such as copy writing and content generation will attract extra fees, which will be communicated promptly."

#### website-pricing-packages ####
website:
  - title : "Standard"
    subtitle: "Best for small businesses and professionals just starting out on their digital journey"
    price : "KSH. 12,000"
    link : "https://docs.google.com/forms/d/e/1FAIpQLSfbI4gmqs3-hA3axMu7_m4b_9nfi7NLzNaHQglYdyF5xgUgzA/viewform?usp=pp_url&entry.321104941=Standard&entry.826318386=Email+Only"
    label : "Express Interest"
    features :
      - "Turnaround: 5-7 Business Days"
      - "Custom Website Domain e.g yourbusiness.com"
      - "One Year Website Hosting"
      - "Secure your Site with SSL Certificate"
      - "Three Months Free Website Maintenance"
      - "Up To 5 Static, Visually-Appealing Pages"
      - "Responsive Design i.e mobile-friendly"
      - "Basic Search Engine Optimization (SEO)"
  - title : "Professional"
    subtitle: "For established businesses who want to engage their audience more in the digital space"
    price : "From KSH. 20,000"
    link : "https://docs.google.com/forms/d/e/1FAIpQLSfbI4gmqs3-hA3axMu7_m4b_9nfi7NLzNaHQglYdyF5xgUgzA/viewform?usp=pp_url&entry.321104941=Professional&entry.826318386=Email+Only"
    label : "Express Interest"
    features :
      - "Turnaround: 10-14 Business Days"
      - "Same benefits as the Standard Package Plus More"
      - "Up To 10 Dynamic Visually-Appealing Pages"
      - "Database Integration"
      - "Google Analytics Integration"
      - "Administrative Dashboard"
      - "Custom logo design"
      - "Custom Emails e.g sales@your-business.com"
      - "Intermediate Search Engine Optimisation (SEO)"
  - title : "Pro Ultra"
    subtitle : "Automate workflows on the web e.g payments, hiring, bookings, etc." 
    price : "From KSH. 35,000"
    link : "https://docs.google.com/forms/d/e/1FAIpQLSfbI4gmqs3-hA3axMu7_m4b_9nfi7NLzNaHQglYdyF5xgUgzA/viewform?usp=pp_url&entry.321104941=Pro+Ultra&entry.826318386=Email+Only"
    label : "Express Interest"
    features :
      - "Turnaround: From 21 Business Days"
      - "Same Benefits as the Standard and Professional packages Plus More"
      - "Live Chat integration"
      - "MPESA, Visa, and Mastercard Payment Integration"
      - "Advanced Google Analytics & SEO"
      - "Automated Custom Workflows"
      - "Shop integration"
      - "CRM integration"
      - "Six Months Free Maintenance"


########################### Branding Pricing ##############################

#### branding-pricing-intro ####
branding-intro:
  - title: "Our Digital Branding Package"
    intro-message: "Our digital branding packages have been tailored to offer value for money as you navigate the digital landscape. Select from one of our packages below:"
    warning: "Note: Services tangential to branding design, such as copy writing, content generation, photography, etc., will attract extra fees, which will be communicated promptly."

#### branding-pricing-packages ####
branding:
  - title : "Starter"
    subtitle: "Logo + Colours + Business Cards"
    price : "KSH. 10,000"
    link : "https://forms.gle/gwNcAqXMhpLdrTZm8"
    label : "Express Interest"
    features :
      - "Turnaround: 3-5 Business Days"
      - "Two Custom Logos to Choose From"
      - "Professional Business Card Design"
      - "Help Selecting Brand Colors"
      - "Logo & Brand Colour Mockups"
      - "Professional Letter Head"
      - "Professional Eamil Header"
  - title : "Silver"
    subtitle: "Starter Package + Social Media"
    price : "KSH. 15,000"
    link : "https://forms.gle/gwNcAqXMhpLdrTZm8"
    label : "Express Interest"
    features :
      - "Turnaround: 7-10 Business Days"
      - "Everything in the Starter Package Plus:"
      - "Social Media Banners (Facebook, Twitter, Instagram, WhatsApp, LinkedIn)"
      - "Three Custom Logos to Choose from"
      - "Social Media Post Template with your Logo + Colours"
      - "Three Posters Outlining Your Services"
  - title : "Enterprise"
    subtitle: "Custom & Advanced Digital Branding"
    price : "From KSH. 25,000"
    link : "https://forms.gle/gwNcAqXMhpLdrTZm8"
    label : "Express Interest"
    features :
      - "Turnaround: From 14 Business Days"
      - "Set Up Social Media (Facebook, Twitter, Instagram, WhatsApp, LinkedIn)"
      - "Set Up WhatsApp Business"
      - "Digital Ad Campaigns"
      - "Design Merchandise, such as T-shirts, notebooks, etc"
      - "Deploying CRMs"




################## About ###########################
about:
  enable : true
  subtitle : "About"
  title : "Design & <br>Development"
  image : "/assets/images/about/about.png"
  content : "Hilary Onyango Okello is the brains behind
OnyangoOkello.com. And he has been designing and building software professionaly since 2022.



Before founding his eponymous studio, Hilary pursued
a bachelor’s degree in construction management
at JKUAT and trained as a certified web developer
at Simplon.co.




When he is not at work, Hilary enjoys gardening and
cooking. He lives in Kisumu, Kenya."
  button:
    enable : true
    label : "Get in Touch"
    link : "#contact"


############################## Social Site ##########################
social:
  - name: "facebook"
    icon: "ti-facebook" # themify icon pack https://themify.me/themify-icons
    link: "#"

  - name: "twitter"
    icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link: "#"

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "#"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "#"